// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDj9wj_UeN7XSQZr6DZUFEFjQMk0AEPZZ4',
    appId: '1:208506254857:web:a5a173d46d8945ab492ad8',
    messagingSenderId: '208506254857',
    projectId: 'hulkifyfinalapp',
    authDomain: 'hulkifyfinalapp.firebaseapp.com',
    storageBucket: 'hulkifyfinalapp.firebasestorage.app',
    measurementId: 'G-GBWJN0TTY5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjYnC9xAbklEthgqJ8dtn6cvRzCr5I75g',
    appId: '1:208506254857:android:e4818ad93cc8b29c492ad8',
    messagingSenderId: '208506254857',
    projectId: 'hulkifyfinalapp',
    storageBucket: 'hulkifyfinalapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHF1PCqMIztfILL-zxk0BCbhXEF8D-5yQ',
    appId: '1:208506254857:ios:c94c68bffe432d99492ad8',
    messagingSenderId: '208506254857',
    projectId: 'hulkifyfinalapp',
    storageBucket: 'hulkifyfinalapp.firebasestorage.app',
    iosBundleId: 'com.example.hulkify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHF1PCqMIztfILL-zxk0BCbhXEF8D-5yQ',
    appId: '1:208506254857:ios:c94c68bffe432d99492ad8',
    messagingSenderId: '208506254857',
    projectId: 'hulkifyfinalapp',
    storageBucket: 'hulkifyfinalapp.firebasestorage.app',
    iosBundleId: 'com.example.hulkify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDj9wj_UeN7XSQZr6DZUFEFjQMk0AEPZZ4',
    appId: '1:208506254857:web:10a6a23fdbb676dd492ad8',
    messagingSenderId: '208506254857',
    projectId: 'hulkifyfinalapp',
    authDomain: 'hulkifyfinalapp.firebaseapp.com',
    storageBucket: 'hulkifyfinalapp.firebasestorage.app',
    measurementId: 'G-H4MMRPLG7J',
  );
}
